### ISSUE TITLE
Width and colors in XML are not working

### ISSUE THREAD

**Issue by ibarrea** [leandroBorgesFerreira/LoadingButtonAndroid#31] opened 2017-11-19 22:16 UTC
This is my xml, and the spinning is still black and the button is still full width of the layout

     <br.com.simplepass.loading_button_lib.customViews.CircularProgressButton
            android:id="@+id/pointsButton"
            android:layout_width="150dp" (or wrap_content)
            android:layout_height="wrap_content"
            android:background="@color/blue"
            android:text="Sumar"
            android:layout_marginTop="15dp"
            android:layout_below="@id/number_picker"
            android:textColor="@color/white"
            android:layout_centerHorizontal="true"
            app:spinning_bar_color="@color/white"
            app:spinning_bar_width="4dp"/>

**Comment by leandroBorgesFerreira** [comment] 2017-11-21 13:46
Just testes in my computer and it is working. Witch version of the library are you using?

**Comment by leandroBorgesFerreira** [comment] 2017-12-23 00:54
I am closing this issue since it can't be reproduced. Feel free to open it again if you think it is necessary

**Closed by leandroBorgesFerreira** 2017-12-23 00:54 UTC
