### ISSUE TITLE
After tap on follow button, I would like to change button text as "follow" or "unfollow",button text is not changed 

### ISSUE THREAD

**Issue by Seroja1010** [leandroBorgesFerreira/LoadingButtonAndroid#15] opened 2017-06-01 14:11 UTC
followBtn.revertAnimation(new OnAnimationEndListener() {
            @Override
            public void onAnimationEnd() {
                if (selectedUser.isFollowing) {
                    followBtn.setText("Unfollow");
                } else {
                    followBtn.setText("Follow");
                }
            }
        });

....
followBtn.revertAnimation();

**Comment by leandroBorgesFerreira** [comment] 2017-06-01 17:40
Witch one are you calling? The first or the second option of code that you presented?

**Comment by Seroja1010** [comment] 2017-06-03 09:31
both case is not working. And when I apply rounded corner shape to button.
Once revert, It's changed rectangle corner

**Comment by leandroBorgesFerreira** [comment] 2017-06-04 22:28
Hi Seroja1010,

I just tested with 1.7.2 version (the current one) and it worked just fine, I believe that you are not setting the value of your sleectedUser.isFollowing properlly. You can test without any logic inside OnEndAnimationListener to make sure that the problem is not in your code.

I also just tested the revert corner. It also works fine. I believe that you are not setting the final corner angle in your XML like this:

`app:finalCornerAngle="50dp"`

If you don't set this variable, it is going to use the default value that is 0dp. So you will end with squared button. Just set the app:finalCornerAngle and you will have a rounded button

**Comment by Seroja1010** [comment] 2017-06-05 01:34
Thanks I will test

**Comment by leandroBorgesFerreira** [comment] 2017-06-08 17:22
Hello Seroja1010, Did the solution worked for you?

**Comment by leandroBorgesFerreira** [comment] 2017-06-14 22:43
@Seroja1010  I am closing this issue assuming that the solution worked for you. Feel free to reopen it if you have any problem

**Closed by leandroBorgesFerreira** 2017-06-14 22:43 UTC

**Comment by ClarkXP** [comment] 2017-11-10 18:07
I have a similar bug, I using CircularProgressImageButton. Then when I call revertAnimation with callback, only is changed the background, isn't changing ImageDrawable and SpinningBarColor.

```java
btnPersonFollow.revertAnimation(new OnAnimationEndListener() {
            @Override
            public void onAnimationEnd() {
                boolean followingOrPending = Arrays.asList(FollowStatus.FollowStatusAccepted, FollowStatus.FollowStatusPending, FollowStatus.FollowStatusRejected).contains(getPerson().followingStatus);
                if (followingOrPending) {
                    viewHolder.btnPersonFollow.setBackgroundResource(R.drawable.bg_button_following);
                    viewHolder.btnPersonFollow.setImageResource(R.drawable.person_check);
                    viewHolder.btnPersonFollow.setSpinningBarColor(ResourcesCompat.getColor(viewHolder.itemView.getResources(),R.color.suda_blue_medium,null));

                } else {
                    viewHolder.btnPersonFollow.setBackgroundResource(R.drawable.bg_button_following_outline);
                    viewHolder.btnPersonFollow.setImageResource(R.drawable.person_add);
                    viewHolder.btnPersonFollow.setSpinningBarColor(ResourcesCompat.getColor(viewHolder.itemView.getResources(),R.color.suda_cyan,null));
                }
            }
        });
```
