### ISSUE TITLE
Null on IsDone

### ISSUE THREAD

**Issue by romreviewer** [leandroBorgesFerreira/LoadingButtonAndroid#84] opened 2018-10-09 21:24 UTC
I am Seeing this issue in my fabric please fix it or help me fix it it very common among users
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void br.com.simplepass.loading_button_lib.a.a.stop()' on a null object reference
       at br.com.simplepass.loading_button_lib.customViews.CircularProgressButton.doneLoadingAnimation(CircularProgressButton.java:297)
       at bombitup.romreviwer.com.bombitup.Count.Newi$33.run(Newi.java:381)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6635)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)`

I am Calling button in handler which is in async task through an object

**Comment by leandroBorgesFerreira** [comment] 2019-01-07 01:06
Hello  @Sanchit43. Sorry for taking too long to answer your issue. This library was updated and the code was completely rewritten in the version 2.0.1. Could you update the library and let me know if the problem still exist?

**Comment by leandroBorgesFerreira** [comment] 2019-05-16 22:07
I am closing as I cannot reproduce it easily. If you still have this problem, please reopen it.

**Closed by leandroBorgesFerreira** 2019-05-16 22:07 UTC
