### ISSUE TITLE
blinking while progress

### ISSUE THREAD

**Issue by pro2on** [leandroBorgesFerreira/LoadingButtonAndroid#8] opened 2017-05-08 17:11 UTC
Hello!

While progress, the arc is blinking. It's like a new step when it becomes it's min size and then become full size and immediately min again  and begin the growing.

Tested on android simulator API 25

**Comment by leandroBorgesFerreira** [comment] 2017-05-09 12:28
Hi pro2on. I will take a look at this problem and answer you a bit later

**Comment by leandroBorgesFerreira** [comment] 2017-05-16 14:07
Hello, pro2on. You are right. There is definitely a blinking... Just saw this in the emulator with api 24 and 25. I am trying to find a real device with android Nougat to see if the problem happens on then.

**Comment by leandroBorgesFerreira** [comment] 2017-05-16 14:13
Just tested on a Samsung Galaxy S7 with api 24. Didn't see the problem. I will keep looking

**Comment by leandroBorgesFerreira** [comment] 2017-05-16 14:31
I could reproduce this in an Nexus 6P. I am working to solve this

**Comment by leandroBorgesFerreira** [comment] 2017-06-12 16:27
@victorkvarghese Sorry, but not yet. I am a little bit busy with some other projects. But I will take care of it as soon as I can

**Comment by Cataclismo** [comment] 2017-07-21 14:20
Any news about this? Thanks :)

**Comment by leandroBorgesFerreira** [comment] 2017-07-24 02:45
@Cataclismo I finally fixed the problem. You can use the 1.8.0 version, the problem was fixed in this version

**Closed by leandroBorgesFerreira** 2017-07-24 02:45 UTC

**Comment by leandroBorgesFerreira** [comment] 2017-07-24 03:26
By the way: this was a hard one!

**Comment by Cataclismo** [comment] 2017-07-24 15:29
@leandroBorgesFerreira Thank you a lot. The library is amazing, by the way. Nice job :)

**Comment by leandroBorgesFerreira** [comment] 2017-07-24 17:29
You are welcome!
